export default [
  {
    details: {
      block: '1',
      number: '1',
      address: 'rua da quadra 1 lote 1. rua da quadra 1 lote 1. rua da quadra 1 lote 1. rua da quadra 1 lote 1.',
      area: '9.653,87 m²',
      shape: 'Retângulo',
      dimensions: 'Base: 100m. Altura: 50m.',
      deed: 'ESCRITURA QUADRA 1 LOTE 1',
      deedDate: '21/06/1994',
      registry: 'REGISTRO QUADRA 1 LOTE 1. REGISTRO QUADRA 1 LOTE 1. REGISTRO QUADRA 1 LOTE 1.',
      observations: 'QUADRA 1 LOTE 1 observervação. QUADRA 1 LOTE 1 observervação. QUADRA 1 LOTE 1 observervação.\nQUADRA 1 LOTE 1 observervação. QUADRA 1 LOTE 1 observervação. QUADRA 1 LOTE 1 observervação.',
    },
    sale: {
      details: {
        openAt: '21/06/1990',
        closeAt: '21/09/1990',
        installmentCount: '3',
        price: 'R$ 3.000,90',
        downPayment: 'R$ 3.000,90',
        paymentType: 'Parcelado',
        progress: 'Aberto',
      },
      buyers: [
        {
          fullName: 'Vitória Teixeira Sampaio Da Silva',
          cpf: '134.889.266-36',
          cnpj: 'Não informado',
          landLinePhone: '(031) 3330-4333',
          mobilePhone: 'Não informado',
          email: 'vitoriateixeira@gmail.com',
          address: 'Rua Paracatu, Bairro Parque Imperial, 598',
          city: 'São Paulo',
          state: 'São Paulo',
          cep: '03962-040',
        },
      ],
      installments: [
        {
          price: 'R$ 1.000,30',
          paymentDate: '21/07/1990',
          progress: 'Pendente',
        },
        {
          price: 'R$ 1.000,30',
          paymentDate: '21/08/1990',
          progress: 'Pendente',
        },
        {
          price: 'R$ 1.000,30',
          paymentDate: '21/09/1990',
          progress: 'Pendente',
        },
      ],
    },
  },
  {
    details: {
      block: '1',
      number: '2',
      address: 'rua da quadra 1 lote 2. rua da quadra 1 lote 2. rua da quadra 1 lote 2. rua da quadra 1 lote 2.',
      area: '8.660,6 m²',
      shape: 'Retângulo',
      dimensions: 'Base: 100m. Altura: 50m.',
      deed: 'ESCRITURA QUADRA 1 LOTE 2',
      deedDate: '22/07/1995',
      registry: 'REGISTRO QUADRA 1 LOTE 2. REGISTRO QUADRA 1 LOTE 2. REGISTRO QUADRA 1 LOTE 2.',
      observations: 'QUADRA 1 LOTE 2 observervação. QUADRA 1 LOTE 2 observervação. QUADRA 1 LOTE 2 observervação.\nQUADRA 1 LOTE 2 observervação. QUADRA 1 LOTE 2 observervação. QUADRA 1 LOTE 2 observervação.',
    },
    sale: {
      details: {
        openAt: '22/05/2015',
        closeAt: '22/05/2015',
        installmentCount: '0',
        price: 'R$ 670.523,14',
        downPayment: 'R$ 670.523,14',
        paymentType: 'Vista',
        progress: 'Fechado',
      },
      buyers: [
        {
          fullName: 'Julia Fogaça Teixeira',
          cpf: '135.889.288-86',
          cnpj: 'Não informado',
          landLinePhone: 'Não informado',
          mobilePhone: '(033) 91031-4294',
          email: 'juliafogaca@uol.com.br',
          address: 'Rua Maria Luísa do Val Penteado, Bairro São Matheus, 64',
          city: 'São Paulo',
          state: 'São Paulo',
          cep: '06662-040',
        },
      ],
      installments: null,
    },
  },
  {
    details: {
      block: '1',
      number: '3',
      address: 'rua da quadra 1 lote 3. rua da quadra 1 lote 3. rua da quadra 1 lote 3. rua da quadra 1 lote 3.',
      area: '6770.7',
      shape: 'Irregular',
      dimensions: 'Direita: 100m. Esquerda: 100m. Frente-lateral-esquerda: 50m.',
      deed: 'ESCRITURA QUADRA 1 LOTE 3',
      deedDate: '23/08/1996',
      registry: 'REGISTRO QUADRA 1 LOTE 3. REGISTRO QUADRA 1 LOTE 3. REGISTRO QUADRA 1 LOTE 3.',
      observations: 'QUADRA 1 LOTE 3 observervação. QUADRA 1 LOTE 3 observervação. QUADRA 1 LOTE 3 observervação.\nQUADRA 1 LOTE 3 observervação. QUADRA 1 LOTE 3 observervação. QUADRA 1 LOTE 3 observervação.',
    },
    sale: {
      details: {
        openAt: '02/09/1980',
        closeAt: '02/11/1980',
        installmentCount: '2',
        price: 'R$ 2.000.66',
        downPayment: 'R$ 2.000.66',
        paymentType: 'Parcelado',
        progress: 'Fechado',
      },
      buyers: [
        {
          fullName: 'Emanuelly Araújo Denk',
          cpf: '132.877.262-33',
          cnpj: 'Não informado',
          landLinePhone: '(077) 3555-0983',
          mobilePhone: 'Não informado',
          email: 'emanudenk@gmail.com',
          address: 'Rua Rua Domingos Olímpio, Bairro Centro, 304',
          city: 'Sobral',
          state: 'Ceará',
          cep: '62011-140',
        },
      ],
      installments: [
        {
          price: '1.000.33',
          paymentDate: '02/10/1980',
          progress: 'Quitado',
        },
        {
          price: '1.000.33',
          paymentDate: '02/11/1980',
          progress: 'Quitado',
        },
      ],
    },
  },
  {
    details: {
      block: '2',
      number: '1',
      address: 'rua da quadra 2 lote 1. rua da quadra 2 lote 1. rua da quadra 2 lote 1. rua da quadra 2 lote 1.',
      area: '5660.6',
      shape: 'Irregular',
      dimensions: 'Direita: 100m. Esquerda: 100m. Frente-lateral-esquerda: 50m.',
      deed: 'ESCRITURA QUADRA 2 LOTE 1',
      deedDate: '24/09/1997',
      registry: 'REGISTRO QUADRA 2 LOTE 1. REGISTRO QUADRA 2 LOTE 1. REGISTRO QUADRA 2 LOTE 1.',
      observations: 'QUADRA 2 LOTE 1 observervação. QUADRA 2 LOTE 1 observervação. QUADRA 2 LOTE 1 observervação.\nQUADRA 2 LOTE 1 observervação. QUADRA 2 LOTE 1 observervação. QUADRA 2 LOTE 1 observervação.',
    },
    sale: {
      details: {
        openAt: '01/02/1993',
        closeAt: '01/02/1993',
        installmentCount: '0',
        price: 'R$ 285.606,54',
        downPayment: 'R$ 285.606,54',
        paymentType: 'Vista',
        progress: 'Aberto',
      },
      buyers: [
        {
          fullName: 'Gabriel Martins Lula Da Silva',
          cpf: '024.567.936-44',
          cnpj: 'Não informado',
          landLinePhone: 'Não informado',
          mobilePhone: '(071) 99856-9668',
          email: 'gabrielmatinslula@bol.com',
          address: 'Avenida Rio Branco, Centro, 87',
          city: 'Rio de Janeiro',
          state: 'Rio de Janeiro',
          cep: '20040-002',
        },
      ],
      installments: null,
    },
  },
  {
    details: {
      block: '2',
      number: '2',
      address: 'rua da quadra 2 lote 2. rua da quadra 2 lote 2. rua da quadra 2 lote 2. rua da quadra 2 lote 2.',
      area: '31.400 m²',
      shape: 'Circular',
      dimensions: 'Raio: 100m.',
      deed: 'ESCRITURA QUADRA 2 LOTE 2',
      deedDate: '25/10/1998',
      registry: 'REGISTRO QUADRA 2 LOTE 2. REGISTRO QUADRA 2 LOTE 2. REGISTRO QUADRA 2 LOTE 2.',
      observations: 'QUADRA 2 LOTE 2 observervação. QUADRA 2 LOTE 2 observervação. QUADRA 2 LOTE 2 observervação.\nQUADRA 2 LOTE 2 observervação. QUADRA 2 LOTE 2 observervação. QUADRA 2 LOTE 2 observervação.',
    },
    sale: null,
  },
  {
    details: {
      block: '3',
      number: '1',
      address: 'rua da quadra 3 lote 1. rua da quadra 3 lote 1. rua da quadra 3 lote 1. rua da quadra 3 lote 1.',
      area: '31400',
      shape: 'Retângulo',
      dimensions: 'Base: 100m. Altura: 50m.',
      deed: 'ESCRITURA QUADRA 3 LOTE 1',
      deedDate: '26/11/1999',
      registry: 'REGISTRO QUADRA 3 LOTE 1. REGISTRO QUADRA 3 LOTE 1. REGISTRO QUADRA 3 LOTE 1.',
      observations: 'QUADRA 3 LOTE 1 observervação. QUADRA 3 LOTE 1 observervação. QUADRA 3 LOTE 1 observervação.\nQUADRA 3 LOTE 1 observervação. QUADRA 3 LOTE 1 observervação. QUADRA 3 LOTE 1 observervação.',
    },
    sale: null,
  },
  {
    details: {
      block: '4',
      number: '1',
      address: 'rua da quadra 4 lote 1. rua da quadra 4 lote 1. rua da quadra 4 lote 1. rua da quadra 4 lote 1.',
      area: '41600.6',
      shape: 'Retângulo',
      dimensions: 'Base: 100m. Altura: 50m.',
      deed: 'ESCRITURA QUADRA 4 LOTE 1',
      deedDate: '27/12/2999',
      registry: 'REGISTRO QUADRA 4 LOTE 1. REGISTRO QUADRA 4 LOTE 1. REGISTRO QUADRA 4 LOTE 1.',
      observations: 'QUADRA 4 LOTE 1 observervação. QUADRA 4 LOTE 1 observervação. QUADRA 4 LOTE 1 observervação.\nQUADRA 4 LOTE 1 observervação. QUADRA 4 LOTE 1 observervação. QUADRA 4 LOTE 1 observervação.',
    },
    sale: {
      details: {
        openAt: '15/05/2010',
        closeAt: '15/05/2010',
        installmentCount: '0',
        price: 'R$ 777,87',
        downPayment: 'R$ 777,87',
        paymentType: 'Vista',
        progress: 'Fechado',
      },
      buyers: [
        {
          fullName: 'Miguel Mendes Barbosa',
          cpf: '754.527.676-12',
          cnpj: 'Não informado',
          landLinePhone: 'Não informado',
          mobilePhone: '(030) 93273-6260',
          email: 'miguelbarbosa@gmail.com',
          address: 'Avenida Esbertalina Barbosa Damiani, Guriri Norte, 157',
          city: 'São Mateus',
          state: 'Espirito Santo',
          cep: '29946-490',
        },
      ],
      installments: [
        {
          price: 'R$ 100,10',
          paymentDate: '15/02/1985',
          progress: 'Quitado',
        },
        {
          price: 'R$ 100,10',
          paymentDate: '15/02/1990',
          progress: 'Quitado',
        },
        {
          price: 'R$ 100,10',
          paymentDate: '15/02/1995',
          progress: 'Pendente',
        },
        {
          price: 'R$ 100,10',
          paymentDate: '15/02/2000',
          progress: 'Pendente',
        },
        {
          price: 'R$ 100,10',
          paymentDate: '15/02/2005',
          progress: 'Pendente',
        },
        {
          price: 'R$ 100,10',
          paymentDate: '15/02/2010',
          progress: 'Pendente',
        },
      ],
    },
  },
  {
    details: {
      block: '4',
      number: '2',
      address: 'rua da quadra 4 lote 2. rua da quadra 4 lote 2. rua da quadra 4 lote 2. rua da quadra 4 lote 2.',
      area: '42200.2',
      shape: 'Retângulo',
      dimensions: 'Base: 100m. Altura: 50m.',
      deed: 'ESCRITURA QUADRA 4 LOTE 2',
      deedDate: '28/01/2001',
      registry: 'REGISTRO QUADRA 4 LOTE 2. REGISTRO QUADRA 4 LOTE 2. REGISTRO QUADRA 4 LOTE 2.',
      observations: 'QUADRA 4 LOTE 2 observervação. QUADRA 4 LOTE 2 observervação. QUADRA 4 LOTE 2 observervação.\nQUADRA 4 LOTE 2 observervação. QUADRA 4 LOTE 2 observervação. QUADRA 4 LOTE 2 observervação.',
    },
    sale: {
      details: {
        openAt: '13/03/2003',
        closeAt: '16/03/2003',
        installmentCount: '0',
        price: 'R$ 880,80',
        downPayment: 'R$ 808,80',
        paymentType: 'Vista',
        progress: 'Fechado',
      },
      buyers: [
        {
          fullName: 'Miguel Mendes Barbosa',
          cpf: '754.527.676-12',
          cnpj: 'Não informado',
          landLinePhone: 'Não informado',
          mobilePhone: '(030) 93273-6260',
          email: 'miguelbarbosa@gmail.com',
          address: 'Avenida Esbertalina Barbosa Damiani, Guriri Norte, 157',
          city: 'São Mateus',
          state: 'Espirito Santo',
          cep: '29946-490',
        },
      ],
      installments: null,
    },
  },
  {
    details: {
      block: '5',
      number: '1',
      address: 'rua da quadra 5 lote 1. rua da quadra 5 lote 1. rua da quadra 5 lote 1. rua da quadra 5 lote 1.',
      area: '55100.1',
      shape: 'Retângulo',
      dimensions: 'Base: 100m. Altura: 50m.',
      deed: 'ESCRITURA QUADRA 5 LOTE 1',
      deedDate: '28/02/2002',
      registry: 'REGISTRO QUADRA 5 LOTE 1. REGISTRO QUADRA 5 LOTE 1. REGISTRO QUADRA 5 LOTE 1.',
      observations: 'QUADRA 5 LOTE 1 observervação. QUADRA 5 LOTE 1 observervação. QUADRA 5 LOTE 1 observervação.\nQUADRA 5 LOTE 1 observervação. QUADRA 5 LOTE 1 observervação. QUADRA 5 LOTE 1 observervação.',
    },
    sale: {
      details: {
        openAt: '16/02/2000',
        closeAt: '16/02/2000',
        installmentCount: '0',
        price: 'R$ 900,60',
        downPayment: 'R$ 900,60',
        paymentType: 'Vista',
        progress: 'Fechado',
      },
      buyers: [
        {
          fullName: 'Miguel Mendes Barbosa',
          cpf: '754.527.676-12',
          cnpj: 'Não informado',
          landLinePhone: 'Não informado',
          mobilePhone: '(030) 93273-6260',
          email: 'miguelbarbosa@gmail.com',
          address: 'Avenida Esbertalina Barbosa Damiani, Guriri Norte, 157',
          city: 'São Mateus',
          state: 'Espirito Santo',
          cep: '29946-490',
        },
      ],
      installments: null,
    },
  },
  {
    details: {
      block: '6',
      number: '1',
      address: 'rua da quadra 6 lote 1. rua da quadra 6 lote 1. rua da quadra 6 lote 1. rua da quadra 6 lote 1.',
      area: '66100.1',
      shape: 'Retângulo',
      dimensions: 'Base: 100m. Altura: 60m.',
      deed: 'Não informado',
      deedDate: 'Não informado',
      registry: 'REGISTRO QUADRA 6 LOTE 1. REGISTRO QUADRA 6 LOTE 1. REGISTRO QUADRA 6 LOTE 1.',
      observations: 'QUADRA 6 LOTE 1 observervação. QUADRA 6 LOTE 1 observervação. QUADRA 6 LOTE 1 observervação.\nQUADRA 6 LOTE 1 observervação. QUADRA 6 LOTE 1 observervação. QUADRA 6 LOTE 1 observervação.',
    },
    sale: {
      details: {
        openAt: '15/01/1985',
        closeAt: '15/02/2011',
        installmentCount: '6',
        price: 'R$ 600,60',
        downPayment: 'R$ 600,60',
        paymentType: 'Parcelado',
        progress: 'Aberto',
      },
      buyers: [
        {
          fullName: 'Gabriel Martins Lula Da Silva',
          cpf: '024.567.936-44',
          cnpj: 'Não informado',
          landLinePhone: 'Não informado',
          mobilePhone: '(071) 99856-9668',
          email: 'gabrielmatinslula@bol.com',
          address: 'Avenida Rio Branco, Centro, 87',
          city: 'Rio de Janeiro',
          state: 'Rio de Janeiro',
          cep: '20040-002',
        },
      ],
      installments: null,
    },
  },
  {
    details: {
      block: '6',
      number: '2',
      address: 'rua da quadra 6 lote 2. rua da quadra 6 lote 2. rua da quadra 6 lote 2. rua da quadra 6 lote 2.',
      area: '66222.22',
      shape: 'Retângulo',
      dimensions: 'Base: 222m. Altura: 222m.',
      deed: 'Não informado',
      deedDate: 'Não informado',
      registry: 'REGISTRO QUADRA 6 LOTE 2. REGISTRO QUADRA 6 LOTE 2. REGISTRO QUADRA 6 LOTE 2.',
      observations: 'QUADRA 6 LOTE 2 observervação. QUADRA 6 LOTE 2 observervação. QUADRA 6 LOTE 2 observervação.\nQUADRA 6 LOTE 2 observervação. QUADRA 6 LOTE 2 observervação. QUADRA 6 LOTE 2 observervação.',
    },
    sale: {
      details: {
        openAt: '15/01/1980',
        closeAt: '15/01/1980',
        installmentCount: '0',
        price: 'R$ 1.111,60',
        downPayment: 'R$ 1.111,60',
        paymentType: 'Vista',
        progress: 'Fechado',
      },
      buyers: [
        {
          fullName: 'Americanas SA',
          cpf: 'Não informado',
          cnpj: '44.444.444/0001-41',
          landLinePhone: '(031) 3273-6260',
          mobilePhone: 'Não informado',
          email: 'sac@americanas.com',
          address: 'Avenida Contorno, Patio Savassi, 59',
          city: 'Belo Horizonte',
          state: 'Minas Gerais',
          cep: '30946-490',
        },
        {
          fullName: 'Lotedor Company',
          cpf: 'Não informado',
          cnpj: '77.474.774/0001-71',
          landLinePhone: '(031) 3333-3333',
          mobilePhone: 'Não informado',
          email: 'sac@lotedorcompany.com',
          address: 'Avenida Savassi, Bairro Contorno, 942',
          city: 'Salvador',
          state: 'Bahia',
          cep: '40444-490',
        },
      ],
      installments: null,
    },
  },
];
